/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			pAccountModule.useMethodDescrAlias = true;
			ScriptModule pPlayerAvatarModule = new ScriptModule("PlayerAvatar");
			EntityDef.moduledefs["PlayerAvatar"] = pPlayerAvatarModule;
			EntityDef.idmoduledefs[2] = pPlayerAvatarModule;

			Property pPlayerAvatar_position = new Property();
			pPlayerAvatar_position.name = "position";
			pPlayerAvatar_position.properUtype = 40000;
			pPlayerAvatar_position.properFlags = 4;
			pPlayerAvatar_position.aliasID = 1;
			Vector3 PlayerAvatar_position_defval = new Vector3();
			pPlayerAvatar_position.defaultVal = PlayerAvatar_position_defval;
			pPlayerAvatarModule.propertys["position"] = pPlayerAvatar_position; 

			pPlayerAvatarModule.usePropertyDescrAlias = true;
			pPlayerAvatarModule.idpropertys[(UInt16)pPlayerAvatar_position.aliasID] = pPlayerAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(PlayerAvatar), property(position / 40000).");

			Property pPlayerAvatar_direction = new Property();
			pPlayerAvatar_direction.name = "direction";
			pPlayerAvatar_direction.properUtype = 40001;
			pPlayerAvatar_direction.properFlags = 4;
			pPlayerAvatar_direction.aliasID = 2;
			Vector3 PlayerAvatar_direction_defval = new Vector3();
			pPlayerAvatar_direction.defaultVal = PlayerAvatar_direction_defval;
			pPlayerAvatarModule.propertys["direction"] = pPlayerAvatar_direction; 

			pPlayerAvatarModule.usePropertyDescrAlias = true;
			pPlayerAvatarModule.idpropertys[(UInt16)pPlayerAvatar_direction.aliasID] = pPlayerAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(PlayerAvatar), property(direction / 40001).");

			Property pPlayerAvatar_spaceID = new Property();
			pPlayerAvatar_spaceID.name = "spaceID";
			pPlayerAvatar_spaceID.properUtype = 40002;
			pPlayerAvatar_spaceID.properFlags = 16;
			pPlayerAvatar_spaceID.aliasID = 3;
			UInt32 PlayerAvatar_spaceID_defval;
			UInt32.TryParse("", out PlayerAvatar_spaceID_defval);
			pPlayerAvatar_spaceID.defaultVal = PlayerAvatar_spaceID_defval;
			pPlayerAvatarModule.propertys["spaceID"] = pPlayerAvatar_spaceID; 

			pPlayerAvatarModule.usePropertyDescrAlias = true;
			pPlayerAvatarModule.idpropertys[(UInt16)pPlayerAvatar_spaceID.aliasID] = pPlayerAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(PlayerAvatar), property(spaceID / 40002).");

			List<DATATYPE_BASE> pPlayerAvatar_enterBattleSpace_args = new List<DATATYPE_BASE>();

			Method pPlayerAvatar_enterBattleSpace = new Method();
			pPlayerAvatar_enterBattleSpace.name = "enterBattleSpace";
			pPlayerAvatar_enterBattleSpace.methodUtype = 4;
			pPlayerAvatar_enterBattleSpace.aliasID = 1;
			pPlayerAvatar_enterBattleSpace.args = pPlayerAvatar_enterBattleSpace_args;

			pPlayerAvatarModule.methods["enterBattleSpace"] = pPlayerAvatar_enterBattleSpace; 
			pPlayerAvatarModule.useMethodDescrAlias = true;
			pPlayerAvatarModule.idmethods[(UInt16)pPlayerAvatar_enterBattleSpace.aliasID] = pPlayerAvatar_enterBattleSpace;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(PlayerAvatar), method(enterBattleSpace / 4).");

			List<DATATYPE_BASE> pPlayerAvatar_notify_match_info_args = new List<DATATYPE_BASE>();
			pPlayerAvatar_notify_match_info_args.Add(EntityDef.id2datatypes[2]);

			Method pPlayerAvatar_notify_match_info = new Method();
			pPlayerAvatar_notify_match_info.name = "notify_match_info";
			pPlayerAvatar_notify_match_info.methodUtype = 5;
			pPlayerAvatar_notify_match_info.aliasID = 2;
			pPlayerAvatar_notify_match_info.args = pPlayerAvatar_notify_match_info_args;

			pPlayerAvatarModule.methods["notify_match_info"] = pPlayerAvatar_notify_match_info; 
			pPlayerAvatarModule.useMethodDescrAlias = true;
			pPlayerAvatarModule.idmethods[(UInt16)pPlayerAvatar_notify_match_info.aliasID] = pPlayerAvatar_notify_match_info;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(PlayerAvatar), method(notify_match_info / 5).");

			List<DATATYPE_BASE> pPlayerAvatar_onEnter_args = new List<DATATYPE_BASE>();

			Method pPlayerAvatar_onEnter = new Method();
			pPlayerAvatar_onEnter.name = "onEnter";
			pPlayerAvatar_onEnter.methodUtype = 3;
			pPlayerAvatar_onEnter.aliasID = 3;
			pPlayerAvatar_onEnter.args = pPlayerAvatar_onEnter_args;

			pPlayerAvatarModule.methods["onEnter"] = pPlayerAvatar_onEnter; 
			pPlayerAvatarModule.useMethodDescrAlias = true;
			pPlayerAvatarModule.idmethods[(UInt16)pPlayerAvatar_onEnter.aliasID] = pPlayerAvatar_onEnter;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(PlayerAvatar), method(onEnter / 3).");

			List<DATATYPE_BASE> pPlayerAvatar_reqMatch_args = new List<DATATYPE_BASE>();

			Method pPlayerAvatar_reqMatch = new Method();
			pPlayerAvatar_reqMatch.name = "reqMatch";
			pPlayerAvatar_reqMatch.methodUtype = 2;
			pPlayerAvatar_reqMatch.aliasID = -1;
			pPlayerAvatar_reqMatch.args = pPlayerAvatar_reqMatch_args;

			pPlayerAvatarModule.methods["reqMatch"] = pPlayerAvatar_reqMatch; 
			pPlayerAvatarModule.base_methods["reqMatch"] = pPlayerAvatar_reqMatch;

			pPlayerAvatarModule.idbase_methods[pPlayerAvatar_reqMatch.methodUtype] = pPlayerAvatar_reqMatch;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(PlayerAvatar), method(reqMatch / 2).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UINT64";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "UINT32";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_ID";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "AVATAR_INFO";
				DATATYPE_AVATAR_INFO datatype = new DATATYPE_AVATAR_INFO();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "AVATAR_INFO_LIST";
				DATATYPE_AVATAR_INFO_LIST datatype = new DATATYPE_AVATAR_INFO_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}